#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-1 -d 1 2 3 
bspc monitor HDMI-2 -d 4 5 6

$HOME/.config/polybar/launch.sh

bspc config normal_border_color "#69677e"
bspc config focused_border_color "#ca356e"

bspc config border_width	3
bspc config window_gap		6

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

